### PR TITLE
Add gate tests for property.

### PR DESCRIPTION
**Pull request by fujiishigeki**
Please check this.

### CODE REVIEW

**Comment by massn** [comment]
LGTM

**Comment by FumiKobayashi** [comment]
LGTM

**Comment by fujiishigeki** [comment]
Please run the flowing command to test.
$ ./script/build_gcc.sh
$ cd build
$ make test

**Comment by FumiKobayashi** [comment]
LGTM

**Comment by yoshioka1128** [comment]
When I executed the last command "make test", I got the following error message.
　clang: error: unsupported option '-fopenmp'

The following commands were executed but did not resolve the problem.
　brew install llvm
　brew install llvm libomp

**Pull request merged**
