### PR TITLE
Yoshioka/sample

### PR DESCRIPTION
**Pull request by yoshioka1128**

### CODE REVIEW

**Comment by yoshioka1128** [comment]
OK

**Comment by yoshioka1128** [comment]
LGTM

**Comment by rsobt** [comment]
LGTM

**Comment by fujiishigeki** [comment]
LGMT

**Comment by FumiKobayashi** [comment]
LGTM

**Comment by yoshioka1128** [comment]
LGTM

**Comment by yoshioka1128** [comment]
LGTM

**Comment by yoshioka1128** [comment]
LGTM

**Comment by yoshioka1128** [comment]
LGTM

**Comment by massn** [comment]
LGTM

**Comment by yoshioka1128** [comment]
LGTM

**Comment by yoshioka1128** [comment]
LGTM

**Comment by yoshioka1128** [comment]
LGTM

**Pull request merged**
